#ifndef MATMUL_DMA_H
#define MATMUL_DMA_H

#include "common_func.h"

#define MATMUL_DMA_BASE_ADDR          0xbf300000u
#define MATMUL_DMA_CTRL_ADDR          (MATMUL_DMA_BASE_ADDR + 0x00u)
#define MATMUL_DMA_STATUS_ADDR        (MATMUL_DMA_BASE_ADDR + 0x04u)
#define MATMUL_DMA_SRC_BASE_ADDR      (MATMUL_DMA_BASE_ADDR + 0x08u)
#define MATMUL_DMA_DST_BASE_ADDR      (MATMUL_DMA_BASE_ADDR + 0x0cu)
#define MATMUL_DMA_GROUP_NUM_ADDR     (MATMUL_DMA_BASE_ADDR + 0x10u)
#define MATMUL_DMA_CRC32_ADDR         (MATMUL_DMA_BASE_ADDR + 0x20u)
#define MATMUL_DMA_READ_GROUPS_ADDR   (MATMUL_DMA_BASE_ADDR + 0x24u)
#define MATMUL_DMA_DBG_START_ADDR      (MATMUL_DMA_BASE_ADDR + 0x28u)
#define MATMUL_DMA_DBG_FIRST_R_ADDR    (MATMUL_DMA_BASE_ADDR + 0x2cu)
#define MATMUL_DMA_DBG_LAST_R_ADDR     (MATMUL_DMA_BASE_ADDR + 0x30u)
#define MATMUL_DMA_DBG_LAST_CORE_ADDR  (MATMUL_DMA_BASE_ADDR + 0x34u)
#define MATMUL_DMA_DBG_CRC_ADDR        (MATMUL_DMA_BASE_ADDR + 0x38u)
#define MATMUL_DMA_DBG_R_EMPTY_ADDR    (MATMUL_DMA_BASE_ADDR + 0x3cu)
#define MATMUL_DMA_DBG_CORE_STALL_ADDR (MATMUL_DMA_BASE_ADDR + 0x40u)

#define MATMUL_DMA_STATUS_BUSY        0x00000001u
#define MATMUL_DMA_STATUS_DONE        0x00000002u
#define MATMUL_DMA_STATUS_ERROR       0x00000004u
#define MATMUL_DMA_MAX_GROUPS         5000u

int MATMUL_DMA_Start(U32 src_phys, U32 dst_phys, U32 groups);
int MATMUL_DMA_Wait(U32 timeout_polls);
U32 MATMUL_DMA_Get_Status(void);
U32 MATMUL_DMA_Get_CRC32(void);
U32 MATMUL_DMA_Get_Read_Groups(void);

#endif
